### ISSUE TITLE
Todo for MVP

### ISSUE THREAD

**Issue by SandersAaronD** [grafana/ai-training-observability#2]
This is a checklist for our MVP. Essential is essential, nice to have is nice to have; if any individual "nice to have" blocks us for an extended period we probably prefer to launch so that we can get feedback because it is possible to likely that early adopters will have asks that will be 1) easy to deliver and 2) not things we will think of otherwise.

```[tasklist]
### Essential
- [ ] Instrument training code with one import, providing a token, and calling an .init function
- [ ] Implement custom logging of JSON with sane default visualizations
- [ ] Provide basic infrastructure monitoring
- [ ] Successfully monitor "processes" grouped into "runs" belonging to "projects" with UI drill down
```

```[tasklist]
### Nice to have
- [ ] Ensure alerting integration for stalled or finished jobs
- [ ] Allow custom groupings with "runs" as default and easy sorting through processes or runs
- [ ] Enable users to download their data directly for analysis
- [ ] Implement GPU code profiling
- [ ] Provide detailed infrastructure monitoring with dgcm and node exporter
- [ ] Implement tracing for distributed jobs
- [ ] Correlate underlying infrastructure (e.g., kubernetes, slurm) with the job being run
- [ ] Integrate with existing Grafana agent/alloy installation for reliability
- [ ] Ensure the highest possible level of reliability for cases without Grafana agent/alloy
```
